import { FashionItem, Rental } from '../types';

export const MOCK_ITEMS: FashionItem[] = [
  {
    id: '1',
    name: 'Summer Floral Dress',
    brand: 'Zara',
    category: 'Dress',
    size: 'M',
    dailyPrice: 8,
    weeklyPrice: 45,
    image: 'https://via.placeholder.com/300x400/FF6B9D/fff?text=Summer+Dress',
    rating: 4.8,
    carbonSaved: 15,
    description: 'Beautiful floral summer dress, perfect for outdoor events and parties.',
    condition: 'Like New',
    owner: 'Sarah M.',
    ownerAddress: '0x1234...5678',
    available: true,
    location: 'Downtown, 2.3 km away',
  },
  {
    id: '2',
    name: 'Leather Biker Jacket',
    brand: 'H&M',
    category: 'Jacket',
    size: 'L',
    dailyPrice: 12,
    weeklyPrice: 70,
    image: 'https://via.placeholder.com/300x400/4ADE80/fff?text=Leather+Jacket',
    rating: 4.9,
    carbonSaved: 28,
    description: 'Classic leather jacket, genuine leather with metal zippers.',
    condition: 'Good',
    owner: 'Mike T.',
    ownerAddress: '0xabcd...efgh',
    available: true,
    location: 'Midtown, 1.5 km away',
  },
  {
    id: '3',
    name: 'Designer Slim Jeans',
    brand: "Levi's",
    category: 'Pants',
    size: '32',
    dailyPrice: 6,
    weeklyPrice: 35,
    image: 'https://via.placeholder.com/300x400/3B82F6/fff?text=Designer+Jeans',
    rating: 4.7,
    carbonSaved: 12,
    description: 'Slim fit designer jeans, dark wash, perfect condition.',
    condition: 'Like New',
    owner: 'Alex K.',
    ownerAddress: '0x9876...5432',
    available: true,
    location: 'Uptown, 3.1 km away',
  },
  {
    id: '4',
    name: 'Evening Gown',
    brand: 'Gucci',
    category: 'Dress',
    size: 'S',
    dailyPrice: 25,
    weeklyPrice: 150,
    image: 'https://via.placeholder.com/300x400/9333EA/fff?text=Evening+Gown',
    rating: 5.0,
    carbonSaved: 45,
    description: 'Elegant evening gown, perfect for formal events and galas.',
    condition: 'New',
    owner: 'Emma L.',
    ownerAddress: '0xfedc...ba98',
    available: true,
    location: 'West End, 4.2 km away',
  },
  {
    id: '5',
    name: 'Sneakers Limited Edition',
    brand: 'Nike',
    category: 'Shoes',
    size: '10',
    dailyPrice: 10,
    weeklyPrice: 55,
    image: 'https://via.placeholder.com/300x400/EF4444/fff?text=Sneakers',
    rating: 4.6,
    carbonSaved: 8,
    description: 'Limited edition Nike sneakers, barely worn.',
    condition: 'Like New',
    owner: 'Jordan P.',
    ownerAddress: '0x1111...2222',
    available: true,
    location: 'East Side, 2.8 km away',
  },
  {
    id: '6',
    name: 'Designer Handbag',
    brand: 'Louis Vuitton',
    category: 'Accessories',
    size: 'One Size',
    dailyPrice: 20,
    weeklyPrice: 120,
    image: 'https://via.placeholder.com/300x400/F59E0B/fff?text=Handbag',
    rating: 4.9,
    carbonSaved: 20,
    description: 'Authentic Louis Vuitton handbag, classic design.',
    condition: 'Good',
    owner: 'Sophie R.',
    ownerAddress: '0x3333...4444',
    available: true,
    location: 'City Center, 1.2 km away',
  },
];

export const MOCK_RENTALS: Rental[] = [
  {
    id: 'r1',
    itemId: '2',
    itemName: 'Leather Biker Jacket',
    itemImage: 'https://via.placeholder.com/300x400/4ADE80/fff?text=Leather+Jacket',
    startDate: '2025-10-10',
    endDate: '2025-10-17',
    dailyPrice: 12,
    totalPaid: 60,
    status: 'active',
    renterAddress: '0xuser...addr',
    ownerAddress: '0xabcd...efgh',
    depositAmount: 50,
    carbonSaved: 28,
  },
  {
    id: 'r2',
    itemId: '1',
    itemName: 'Summer Floral Dress',
    itemImage: 'https://via.placeholder.com/300x400/FF6B9D/fff?text=Summer+Dress',
    startDate: '2025-09-20',
    endDate: '2025-09-23',
    dailyPrice: 8,
    totalPaid: 24,
    status: 'completed',
    renterAddress: '0xuser...addr',
    ownerAddress: '0x1234...5678',
    depositAmount: 30,
    carbonSaved: 15,
  },
];
